site_name: A320 Knowledge Base
theme:
  name: readthedocs

nav:
  - "A320_Base":
      - Overview: A320_Base/index.md
      - "02 AIRCRAFT INTRODUCTION": A320_Base/02 AIRCRAFT INTRODUCTION.md
      - "05 -20 INTRODUCTION MODULE": A320_Base/05 -20 INTRODUCTION MODULE.md
      - "21 AIR CONDITIONING": A320_Base/21 AIR CONDITIONING.md
      - "22 AUTO FLIGHT": A320_Base/22 AUTO FLIGHT.md
      - "23 COMMUNICATIONS": A320_Base/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER": A320_Base/24 ELECTRICAL POWER.md
      - "25 EQUIPMENT_FURNISHINGS": A320_Base/25 EQUIPMENT_FURNISHINGS.md
      - "26 FIRE PROTECTION": A320_Base/26 FIRE PROTECTION.md
      - "27 FLIGHT CONTROLS": A320_Base/27 FLIGHT CONTROLS.md
      - "27a E-RUDDER PROJECT": A320_Base/27a E-RUDDER PROJECT.md
      - "28 FUEL (Metric Units)": A320_Base/28 FUEL (Metric Units).md
      - "29 HYDRAULIC POWER": A320_Base/29 HYDRAULIC POWER.md
      - "30 ICE & RAIN PROTECTION": A320_Base/30 ICE & RAIN PROTECTION.md
      - "31 INDICATING (Inc ATA 45 - CFDS)": A320_Base/31 INDICATING (Inc ATA 45 - CFDS).md
      - "31 RECORDING SYSTEMS": A320_Base/31 RECORDING SYSTEMS.md
      - "32 LANDING GEAR": A320_Base/32 LANDING GEAR.md
      - "33 LIGHTS": A320_Base/33 LIGHTS.md
      - "34 NAVIGATION": A320_Base/34 NAVIGATION.md
      - "35 OXYGEN": A320_Base/35 OXYGEN.md
      - "36 PNEUMATIC": A320_Base/36 PNEUMATIC.md
      - "38 WATER & WASTE": A320_Base/38 WATER & WASTE.md
      - "46 INFORMATION SYSTEMS": A320_Base/46 INFORMATION SYSTEMS.md
      - "47 INERT GAS SYSTEM": A320_Base/47 INERT GAS SYSTEM.md
      - "49 APU": A320_Base/49 APU.md
      - "51-57 STRUCTURE": A320_Base/51-57 STRUCTURE.md
      - "52 DOORS": A320_Base/52 DOORS.md
      - "70 POWER PLANT (CFM 56)": A320_Base/70 POWER PLANT (CFM 56).md
      - "70 POWER PLANT (IAE V2500)": A320_Base/70 POWER PLANT (IAE V2500).md
      - "Airbus Abbreviations": A320_Base/Airbus Abbreviations.md
      - "IAE V2500 - Engine Manufacturers Notes": A320_Base/IAE V2500 - Engine Manufacturers Notes.md
  - "A320_Neo_LEAP":
      - Overview: A320_Neo_LEAP/index.md
      - "02 INTRODUCTION - PW & CFM": A320_Neo_LEAP/02 INTRODUCTION - PW & CFM.md
      - "23 COMMUNICATIONS": A320_Neo_LEAP/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER - PW & CFM (INT)": A320_Neo_LEAP/24 ELECTRICAL POWER - PW & CFM (INT).md
      - "26 FIRE PROTECTION - LEAP (INT)": A320_Neo_LEAP/26 FIRE PROTECTION - LEAP (INT).md
      - "28 FUEL SYSTEMS - PW & CFM (INT)": A320_Neo_LEAP/28 FUEL SYSTEMS - PW & CFM (INT).md
      - "29 HYDRAULIC POWER - LEAP (INT)": A320_Neo_LEAP/29 HYDRAULIC POWER - LEAP (INT).md
      - "30 ICE AND RAIN PROTECTION - PW & CFM": A320_Neo_LEAP/30 ICE AND RAIN PROTECTION - PW & CFM.md
      - "35 OXYGEN - PW & CFM": A320_Neo_LEAP/35 OXYGEN - PW & CFM.md
      - "36 PNEUMATIC - CFM": A320_Neo_LEAP/36 PNEUMATIC - CFM.md
      - "52 DOORS - PW & CFM": A320_Neo_LEAP/52 DOORS - PW & CFM.md
      - "70-84 ENGINE - A320 NEO (CFM LEAP-1A)": A320_Neo_LEAP/70-84 ENGINE - A320 NEO (CFM LEAP-1A).md
  - "A320_Neo_PW1100":
      - Overview: A320_Neo_PW1100/index.md
      - "02 INTRODUCTION - PW": A320_Neo_PW1100/02 INTRODUCTION - PW.md
      - "23 COMMUNICATIONS": A320_Neo_PW1100/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER - PW (INTERFACE)": A320_Neo_PW1100/24 ELECTRICAL POWER - PW (INTERFACE).md
      - "26 FIRE PROTECTION - PW (INTERFACE)": A320_Neo_PW1100/26 FIRE PROTECTION - PW (INTERFACE).md
      - "28 FUEL SYSTEMS - PW (INTERFACE)": A320_Neo_PW1100/28 FUEL SYSTEMS - PW (INTERFACE).md
      - "29 HYDRAULIC POWER - PW (INTERFACE)": A320_Neo_PW1100/29 HYDRAULIC POWER - PW (INTERFACE).md
      - "35 OXYGEN - PW": A320_Neo_PW1100/35 OXYGEN - PW.md
      - "52 DOORS - PW": A320_Neo_PW1100/52 DOORS - PW.md
      - "70-84 ENGINE - A32X NEO (IAE PW1100G)": A320_Neo_PW1100/70-84 ENGINE - A32X NEO (IAE PW1100G).md
  - "A320_Base":
      - Overview: A320_Base/index.md
      - "02 AIRCRAFT INTRODUCTION": A320_Base/02 AIRCRAFT INTRODUCTION.md
      - "05 -20 INTRODUCTION MODULE": A320_Base/05 -20 INTRODUCTION MODULE.md
      - "21 AIR CONDITIONING": A320_Base/21 AIR CONDITIONING.md
      - "22 AUTO FLIGHT": A320_Base/22 AUTO FLIGHT.md
      - "23 COMMUNICATIONS": A320_Base/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER": A320_Base/24 ELECTRICAL POWER.md
      - "25 EQUIPMENT_FURNISHINGS": A320_Base/25 EQUIPMENT_FURNISHINGS.md
      - "26 FIRE PROTECTION": A320_Base/26 FIRE PROTECTION.md
      - "27 FLIGHT CONTROLS": A320_Base/27 FLIGHT CONTROLS.md
      - "27a E-RUDDER PROJECT": A320_Base/27a E-RUDDER PROJECT.md
      - "28 FUEL (Metric Units)": A320_Base/28 FUEL (Metric Units).md
      - "29 HYDRAULIC POWER": A320_Base/29 HYDRAULIC POWER.md
      - "30 ICE & RAIN PROTECTION": A320_Base/30 ICE & RAIN PROTECTION.md
      - "31 INDICATING (Inc ATA 45 - CFDS)": A320_Base/31 INDICATING (Inc ATA 45 - CFDS).md
      - "31 RECORDING SYSTEMS": A320_Base/31 RECORDING SYSTEMS.md
      - "32 LANDING GEAR": A320_Base/32 LANDING GEAR.md
      - "33 LIGHTS": A320_Base/33 LIGHTS.md
      - "34 NAVIGATION": A320_Base/34 NAVIGATION.md
      - "35 OXYGEN": A320_Base/35 OXYGEN.md
      - "36 PNEUMATIC": A320_Base/36 PNEUMATIC.md
      - "38 WATER & WASTE": A320_Base/38 WATER & WASTE.md
      - "46 INFORMATION SYSTEMS": A320_Base/46 INFORMATION SYSTEMS.md
      - "47 INERT GAS SYSTEM": A320_Base/47 INERT GAS SYSTEM.md
      - "49 APU": A320_Base/49 APU.md
      - "51-57 STRUCTURE": A320_Base/51-57 STRUCTURE.md
      - "52 DOORS": A320_Base/52 DOORS.md
      - "70 POWER PLANT (CFM 56)": A320_Base/70 POWER PLANT (CFM 56).md
      - "70 POWER PLANT (IAE V2500)": A320_Base/70 POWER PLANT (IAE V2500).md
      - "Airbus Abbreviations": A320_Base/Airbus Abbreviations.md
      - "IAE V2500 - Engine Manufacturers Notes": A320_Base/IAE V2500 - Engine Manufacturers Notes.md
  - "A320_Neo_LEAP":
      - Overview: A320_Neo_LEAP/index.md
      - "02 INTRODUCTION - PW & CFM": A320_Neo_LEAP/02 INTRODUCTION - PW & CFM.md
      - "23 COMMUNICATIONS": A320_Neo_LEAP/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER - PW & CFM (INT)": A320_Neo_LEAP/24 ELECTRICAL POWER - PW & CFM (INT).md
      - "26 FIRE PROTECTION - LEAP (INT)": A320_Neo_LEAP/26 FIRE PROTECTION - LEAP (INT).md
      - "28 FUEL SYSTEMS - PW & CFM (INT)": A320_Neo_LEAP/28 FUEL SYSTEMS - PW & CFM (INT).md
      - "29 HYDRAULIC POWER - LEAP (INT)": A320_Neo_LEAP/29 HYDRAULIC POWER - LEAP (INT).md
      - "30 ICE AND RAIN PROTECTION - PW & CFM": A320_Neo_LEAP/30 ICE AND RAIN PROTECTION - PW & CFM.md
      - "35 OXYGEN - PW & CFM": A320_Neo_LEAP/35 OXYGEN - PW & CFM.md
      - "36 PNEUMATIC - CFM": A320_Neo_LEAP/36 PNEUMATIC - CFM.md
      - "52 DOORS - PW & CFM": A320_Neo_LEAP/52 DOORS - PW & CFM.md
      - "70-84 ENGINE - A320 NEO (CFM LEAP-1A)": A320_Neo_LEAP/70-84 ENGINE - A320 NEO (CFM LEAP-1A).md
  - "A320_Neo_PW1100":
      - Overview: A320_Neo_PW1100/index.md
      - "02 INTRODUCTION - PW": A320_Neo_PW1100/02 INTRODUCTION - PW.md
      - "23 COMMUNICATIONS": A320_Neo_PW1100/23 COMMUNICATIONS.md
      - "24 ELECTRICAL POWER - PW (INTERFACE)": A320_Neo_PW1100/24 ELECTRICAL POWER - PW (INTERFACE).md
      - "26 FIRE PROTECTION - PW (INTERFACE)": A320_Neo_PW1100/26 FIRE PROTECTION - PW (INTERFACE).md
      - "28 FUEL SYSTEMS - PW (INTERFACE)": A320_Neo_PW1100/28 FUEL SYSTEMS - PW (INTERFACE).md
      - "29 HYDRAULIC POWER - PW (INTERFACE)": A320_Neo_PW1100/29 HYDRAULIC POWER - PW (INTERFACE).md
      - "35 OXYGEN - PW": A320_Neo_PW1100/35 OXYGEN - PW.md
      - "52 DOORS - PW": A320_Neo_PW1100/52 DOORS - PW.md
      - "70-84 ENGINE - A32X NEO (IAE PW1100G)": A320_Neo_PW1100/70-84 ENGINE - A32X NEO (IAE PW1100G).md


plugins:
  - search

