site_name: A320 Base Knowledge
nav:
  - 02 AIRCRAFT INTRODUCTION: "02 AIRCRAFT INTRODUCTION.md"
  - 05 -20 INTRODUCTION MODULE: "05 -20 INTRODUCTION MODULE.md"
  - 21 AIR CONDITIONING: "21 AIR CONDITIONING.md"
  - 22 AUTO FLIGHT: "22 AUTO FLIGHT.md"
  - 23 COMMUNICATIONS: "23 COMMUNICATIONS.md"
  - 24 ELECTRICAL POWER: "24 ELECTRICAL POWER.md"
  - 25 EQUIPMENT FURNISHINGS: "25 EQUIPMENT_FURNISHINGS.md"
  - 26 FIRE PROTECTION: "26 FIRE PROTECTION.md"
  - 27a E-RUDDER PROJECT: "27a E-RUDDER PROJECT.md"
  - 27 FLIGHT CONTROLS: "27 FLIGHT CONTROLS.md"
  - 28 FUEL (Metric Units): "28 FUEL (Metric Units).md"
  - 29 HYDRAULIC POWER: "29 HYDRAULIC POWER.md"
  - 30 ICE & RAIN PROTECTION: "30 ICE & RAIN PROTECTION.md"
  - 31 INDICATING (Inc ATA 45 - CFDS): "31 INDICATING (Inc ATA 45 - CFDS).md"
  - 31 RECORDING SYSTEMS: "31 RECORDING SYSTEMS.md"
  - 32 LANDING GEAR: "32 LANDING GEAR.md"
  - 33 LIGHTS: "33 LIGHTS.md"
  - 34 NAVIGATION: "34 NAVIGATION.md"
  - 35 OXYGEN: "35 OXYGEN.md"
  - 36 PNEUMATIC: "36 PNEUMATIC.md"
  - 38 WATER & WASTE: "38 WATER & WASTE.md"
  - 46 INFORMATION SYSTEMS: "46 INFORMATION SYSTEMS.md"
  - 47 INERT GAS SYSTEM: "47 INERT GAS SYSTEM.md"
  - 49 APU: "49 APU.md"
  - 51-57 STRUCTURE: "51-57 STRUCTURE.md"
  - 52 DOORS: "52 DOORS.md"
  - 70 POWER PLANT (CFM 56): "70 POWER PLANT (CFM 56).md"
  - 70 POWER PLANT (IAE V2500): "70 POWER PLANT (IAE V2500).md"
  - Airbus Abbreviations: "Airbus Abbreviations.md"
  - IAE V2500 - Engine Manufacturers Notes: "IAE V2500 - Engine Manufacturers Notes.md"
  - index: "index.md"
